version: '3'

services:
  otl-server:
    container_name: otl-server
    restart: always
    build: ./server
    tty: true
    ports:
      - 80:80
      - 443:443
      - 8022:22
    volumes:
      - ./logs:/var/log/apache2
      - ./db:/backup/db
